import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  emptySubText: {
    color: '#666666',
    fontSize: 14,
    marginTop: 8,
  },
  listContent: {
    paddingBottom: 100, 
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 16,
    backgroundColor: '#121212', 
  },
  sectionTitle: {
    color: '#888888',
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    marginRight: 12,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#2A2A2A',
  },
  habitRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.03)', 
  },
  leftContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
  },
  iconWrapper: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  habitName: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '500',
  },
  habitNameFaded: {
    color: '#888888',
  },
  rightContent: {
    width: 60,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingVertical: 14,
  },
  quantRight: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantAmount: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  quantUnit: {
    fontSize: 10,
    color: '#666666',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4, 
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  deleteModalContent: {
    backgroundColor: '#1E1E1E',
    borderRadius: 6,
    width: '100%',
    maxWidth: 400,
    elevation: 5,
    overflow: 'hidden',
  },
  deleteModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 24,
  },
  deleteModalTextContainer: {
    marginLeft: 16,
    flex: 1,
  },
  deleteModalTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  deleteModalText: {
    color: '#888888',
    fontSize: 14,
  },
  deleteModalDivider: {
    height: 1,
    backgroundColor: '#2A2A2A',
    width: '100%',
  },
  deleteModalButtons: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: '#161616',
    gap: 12,
  },
  deleteCancelButton: {
    flex: 1,
    backgroundColor: '#2A2A2A',
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333333',
  },
  deleteCancelText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  deleteConfirmButton: {
    flex: 1,
    backgroundColor: '#D9534F',
    paddingVertical: 12,
    borderRadius: 4,
    alignItems: 'center',
  },
  deleteConfirmText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
  },
  progressModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  progressModalContent: {
    backgroundColor: '#1E1E1E',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    alignItems: 'center',
    elevation: 5,
  },
  progressModalTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  progressModalSub: {
    color: '#888888',
    fontSize: 14,
    marginBottom: 24,
  },
  progressInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 32,
  },
  progressInput: {
    color: '#ffffff',
    fontSize: 48,
    fontWeight: 'bold',
    borderBottomWidth: 2,
    borderBottomColor: '#333',
    minWidth: 80,
    textAlign: 'center',
    paddingVertical: 8,
  },
  progressUnitText: {
    color: '#888888',
    fontSize: 20,
    marginLeft: 12,
    marginBottom: 12,
    fontWeight: '600',
  },
  progressButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  progressCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#333333',
  },
  progressCancelText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  progressSaveBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
  },
  progressSaveText: {
    color: '#121212',
    fontSize: 14,
    fontWeight: 'bold',
  },
  fullScreenModalOverlay: {
    flex: 1,
    backgroundColor: '#121212',
  },
  fullScreenModalContent: {
    flex: 1,
    backgroundColor: '#121212',
  },
  fullScreenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: '#121212',
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E1E',
  },
  headerIconButton: {
    padding: 8,
  },
  fullScreenTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  headerTextButton: {
    padding: 8,
  },
  headerSaveText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  fullScreenScrollContent: {
    padding: 24,
    paddingBottom: 60,
  },
  formRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  labelSwitch: {
    color: '#888888',
    fontSize: 14,
    fontWeight: '600',
  },
  inputGroupFlexible: {
    flex: 1,
    marginRight: 16,
  },
  inputGroupFixed: {
    width: 60,
  },
  label: {
    color: '#888888',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  nameInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E1E1E',
    borderRadius: 8,
    height: 54,
  },
  nameIconSelector: {
    paddingHorizontal: 16,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    height: '100%',
    paddingRight: 16,
  },
  pillInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#050505',
    borderRadius: 9999,
    height: 36,
    paddingHorizontal: 16,
  },
  pillInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 14,
    height: '100%',
  },
  colorBox: {
    width: '100%',
    height: 54,
    borderRadius: 8,
  },
  frequencyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  frequencyToggle: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  minimalDaysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 32,
    paddingHorizontal: 8,
  },
  minimalDayItem: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  minimalDayText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  diRadioWrap: {
    marginBottom: 40,
  },
  diRadioIsland: {
    backgroundColor: '#000000',
    borderRadius: 999,
    padding: 6,
    flexDirection: 'row',
    position: 'relative',
  },
  diRadioIndicator: {
    position: 'absolute',
    top: 6,
    bottom: 6,
    left: 6,
    backgroundColor: '#222222',
    borderRadius: 999,
  },
  diRadioBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    zIndex: 2,
  },
  diRadioBtnText: {
    color: '#aaaaaa',
    fontSize: 13,
    fontWeight: '600',
  },
  diRadioBtnTextActive: {
    color: '#ffffff',
  },
  deleteHabitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    marginTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#1E1E1E',
  },
  deleteHabitText: {
    color: '#FF5252',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 16,
  },
  gridColorCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 4,
    borderColor: 'transparent',
  },
  gridColorCircleActive: {
    borderColor: '#ffffff',
  },
  iconGridRow: {
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  gridIconButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#1E1E1E',
    justifyContent: 'center',
    alignItems: 'center',
  }
});